const animeData = [
  { id: 1, title: "One Piece", synonyms: ["one piece", "op", "onepiece"], poster: "01-one-piece.webp", difficulty: "easy" },
  { id: 2, title: "Naruto", synonyms: ["naruto", "naruto shippuden", "shippuden"], poster: "02-naruto.webp", difficulty: "easy" },
  { id: 3, title: "Death Note", synonyms: ["death note", "deathnote", "dn"], poster: "03-death-note.webp", difficulty: "easy" },
  { id: 4, title: "Attack on Titan", synonyms: ["attack on titan", "aot", "shingeki no kyojin", "snk"], poster: "04-attack-on-titan.webp", difficulty: "easy" },
  { id: 5, title: "Dragon Ball Z", synonyms: ["dragon ball z", "dbz", "dragon ball"], poster: "05-dragon-ball-z.webp", difficulty: "easy" },
  { id: 6, title: "My Hero Academia", synonyms: ["my hero academia", "mha", "boku no hero"], poster: "06-my-hero-academia.webp", difficulty: "easy" },
  { id: 7, title: "Demon Slayer", synonyms: ["demon slayer", "kimetsu no yaiba", "kny"], poster: "07-demon-slayer.webp", difficulty: "easy" },
  { id: 8, title: "Fullmetal Alchemist", synonyms: ["fullmetal alchemist", "fma", "fmab"], poster: "08-fullmetal-alchemist-brotherhood.webp", difficulty: "easy" },
  { id: 9, title: "Sword Art Online", synonyms: ["sword art online", "sao"], poster: "09-sword-art-online.webp", difficulty: "easy" },
  { id: 10, title: "Tokyo Ghoul", synonyms: ["tokyo ghoul", "tg"], poster: "10-tokyo-ghoul.webp", difficulty: "easy" },
  { id: 11, title: "Hunter x Hunter", synonyms: ["hunter x hunter", "hxh"], poster: "11-hunter-x-hunter-2011.webp", difficulty: "easy" },
  { id: 12, title: "Bleach", synonyms: ["bleach"], poster: "12-bleach.webp", difficulty: "easy" },
  { id: 13, title: "Jujutsu Kaisen", synonyms: ["jujutsu kaisen", "jjk"], poster: "13-jujutsu-kaisen.webp", difficulty: "easy" },
  { id: 14, title: "Spy x Family", synonyms: ["spy x family", "spy family"], poster: "14-spy-x-family.webp", difficulty: "easy" },
  { id: 15, title: "Chainsaw Man", synonyms: ["chainsaw man", "csm"], poster: "15-chainsaw-man.webp", difficulty: "easy" },
  { id: 16, title: "One Punch Man", synonyms: ["one punch man", "opm"], poster: "16-one-punch-man.webp", difficulty: "easy" },
  { id: 17, title: "Steins;Gate", synonyms: ["steins gate", "steins;gate"], poster: "17-steins-gate.webp", difficulty: "easy" },
  { id: 18, title: "Code Geass", synonyms: ["code geass"], poster: "18-code-geass.webp", difficulty: "easy" },
  { id: 19, title: "Cowboy Bebop", synonyms: ["cowboy bebop", "bebop"], poster: "19-cowboy-bebop.webp", difficulty: "easy" },
  { id: 20, title: "Neon Genesis Evangelion", synonyms: ["evangelion", "nge", "eva"], poster: "20-neon-genesis-evangelion.webp", difficulty: "easy" },
  { id: 21, title: "Mob Psycho 100", synonyms: ["mob psycho 100", "mob psycho"], poster: "21-mob-psycho-100.webp", difficulty: "easy" },
  { id: 22, title: "Violet Evergarden", synonyms: ["violet evergarden"], poster: "22-violet-evergarden.webp", difficulty: "easy" },
  { id: 23, title: "Your Name", synonyms: ["your name", "kimi no na wa"], poster: "23-your-name.webp", difficulty: "easy" },
  { id: 24, title: "Spirited Away", synonyms: ["spirited away", "chihiro"], poster: "24-spirited-away.webp", difficulty: "easy" },
  { id: 25, title: "Akira", synonyms: ["akira"], poster: "25-akira.webp", difficulty: "easy" },
  { id: 26, title: "Ghost in the Shell", synonyms: ["ghost in the shell", "gits"], poster: "26-ghost-in-the-shell.webp", difficulty: "easy" },
  { id: 27, title: "Toradora", synonyms: ["toradora"], poster: "27-toradora.webp", difficulty: "easy" },
  { id: 28, title: "Re:Zero", synonyms: ["re zero", "rezero"], poster: "28-rezero.webp", difficulty: "easy" },
  { id: 29, title: "The Promised Neverland", synonyms: ["promised neverland", "tpn"], poster: "29-the-promised-neverland.webp", difficulty: "easy" },
  { id: 30, title: "Haikyuu", synonyms: ["haikyuu", "haikyu"], poster: "30-haikyuu.webp", difficulty: "easy" },
  { id: 31, title: "Made in Abyss", synonyms: ["made in abyss", "mia"], poster: "31-made-in-abyss.webp", difficulty: "medium" },
  { id: 32, title: "Vinland Saga", synonyms: ["vinland saga"], poster: "32-vinland-saga.webp", difficulty: "medium" },
  { id: 33, title: "Parasyte", synonyms: ["parasyte", "kiseijuu"], poster: "33-parasyte.webp", difficulty: "medium" },
  { id: 34, title: "Erased", synonyms: ["erased", "boku dake ga inai machi"], poster: "34-erased.webp", difficulty: "medium" },
  { id: 35, title: "Psycho-Pass", synonyms: ["psycho pass", "psychopass"], poster: "35-psycho-pass.webp", difficulty: "medium" },
  { id: 36, title: "Fate/Zero", synonyms: ["fate zero", "fate/zero"], poster: "36-fate-zero.webp", difficulty: "medium" },
  { id: 37, title: "Monogatari Series", synonyms: ["monogatari", "bakemonogatari"], poster: "37-bakemonogatari.webp", difficulty: "medium" },
  { id: 38, title: "March Comes in Like a Lion", synonyms: ["march comes in like a lion", "sangatsu"], poster: "38-march-comes-in-like-a-lion.webp", difficulty: "medium" },
  { id: 39, title: "A Silent Voice", synonyms: ["silent voice", "koe no katachi"], poster: "39-a-silent-voice.webp", difficulty: "medium" },
  { id: 40, title: "Anohana", synonyms: ["anohana"], poster: "40-anohana.webp", difficulty: "medium" },
  { id: 41, title: "Terror in Resonance", synonyms: ["terror in resonance", "zankyou no terror"], poster: "41-terror-in-resonance.webp", difficulty: "medium" },
  { id: 42, title: "Ping Pong the Animation", synonyms: ["ping pong"], poster: "42-ping-pong-the-animation.webp", difficulty: "medium" },
  { id: 43, title: "Mushishi", synonyms: ["mushishi"], poster: "43-mushishi.webp", difficulty: "medium" },
  { id: 44, title: "Baccano", synonyms: ["baccano"], poster: "44-baccano.webp", difficulty: "medium" },
  { id: 45, title: "Durarara", synonyms: ["durarara", "drrr"], poster: "45-durarara.webp", difficulty: "medium" },
  { id: 46, title: "Kill la Kill", synonyms: ["kill la kill"], poster: "46-kill-la-kill.webp", difficulty: "medium" },
  { id: 47, title: "Gurren Lagann", synonyms: ["gurren lagann", "ttgl"], poster: "47-gurren-lagann.webp", difficulty: "medium" },
  { id: 48, title: "FLCL", synonyms: ["flcl", "fooly cooly"], poster: "48-flcl.webp", difficulty: "medium" },
  { id: 49, title: "Beck", synonyms: ["beck"], poster: "49-beck.webp", difficulty: "medium" },
  { id: 50, title: "Space Dandy", synonyms: ["space dandy"], poster: "50-space-dandy.webp", difficulty: "medium" },
  { id: 51, title: "Serial Experiments Lain", synonyms: ["lain", "serial experiments lain"], poster: "51-serial-experiments-lain.webp", difficulty: "hard" },
  { id: 52, title: "Texhnolyze", synonyms: ["texhnolyze"], poster: "52-texhnolyze.webp", difficulty: "hard" },
  { id: 53, title: "Haibane Renmei", synonyms: ["haibane renmei", "haibane"], poster: "53-haibane-renmei.webp", difficulty: "hard" },
  { id: 54, title: "Kaiba", synonyms: ["kaiba"], poster: "54-kaiba.webp", difficulty: "hard" },
  { id: 55, title: "Paranoia Agent", synonyms: ["paranoia agent"], poster: "55-paranoia-agent.webp", difficulty: "hard" },
  { id: 56, title: "Boogiepop Phantom", synonyms: ["boogiepop"], poster: "56-boogiepop-phantom.webp", difficulty: "hard" },
  { id: 57, title: "Mononoke", synonyms: ["mononoke"], poster: "57-mononoke.webp", difficulty: "hard" },
  { id: 58, title: "Tatami Galaxy", synonyms: ["tatami galaxy"], poster: "58-tatami-galaxy.webp", difficulty: "hard" },
  { id: 59, title: "Shouwa Genroku Rakugo Shinjuu", synonyms: ["rakugo"], poster: "59-shouwa-genroku-rakugo-shinjuu.webp", difficulty: "hard" },
  { id: 60, title: "Kyousougiga", synonyms: ["kyousougiga"], poster: "60-kyousougiga.webp", difficulty: "hard" },
  { id: 61, title: "Kemono no Souja Erin", synonyms: ["erin"], poster: "61-kemono-no-souja-erin.webp", difficulty: "hard" },
  { id: 62, title: "Casshern Sins", synonyms: ["casshern sins"], poster: "62-casshern-sins.webp", difficulty: "hard" },
  { id: 63, title: "Gankutsuou", synonyms: ["gankutsuou"], poster: "63-gankutsuou.webp", difficulty: "hard" },
  { id: 64, title: "Kemonozume", synonyms: ["kemonozume"], poster: "64-kemonozume.webp", difficulty: "hard" },
  { id: 65, title: "Mind Game", synonyms: ["mind game"], poster: "65-mind-game.webp", difficulty: "hard" },
  { id: 66, title: "Angel's Egg", synonyms: ["angel's egg", "angels egg"], poster: "66-angels-egg.webp", difficulty: "hard" },
];